import Head from "next/head";
import React from "react";

type LayoutProps = {
  children: React.ReactNode;
};

const PrimaryPageLayout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Bookit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
          integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
          crossOrigin=""
        />
      </Head>
      <main className="min-h-screen bg-primary">{children}</main>
    </>
  );
};

export default PrimaryPageLayout;
