import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Calendar from "../components/calendar/Calendar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bookit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-primary">
        <div className="">
          <Link href="/auth/signin">Zaloguj</Link>
          <Calendar />
        </div>
      </main>
    </>
  );
};

export default Home;
